version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: sand050965/miniroom
    container_name: app
    ports:
      - "8080:8080"
      - "6379:6379"
    network_mode: "host"
    env_file: ./.env
    restart: on-failure
