version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: sand050965/miniroom
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - DB_NAME=${DB_NAME}
      - DB_COLLECTION=${DB_COLLECTION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY_ID}
      - AWS_CLOUDFRONT_URL=${AWS_CLOUDFRONT_URL}
    restart: on-failure
