version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  app:
    image: sand050965/miniroom
    container_name: app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - SECRET=${SECRET}
      - JWT_ACCESS_TOKEN_SECRET=${JWT_ACCESS_TOKEN_SECRET}
      - JWT_REFRESH_TOKEN_SECRET=${JWT_REFRESH_TOKEN_SECRET}
      - SOCKET_IO_ORIGIN=${SOCKET_IO_ORIGIN}
      - DB_URI=${DB_URI}
      - MAIL_SERVICE=${MAIL_SERVICE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_SIGNATURE_VERSION=${AWS_SIGNATURE_VERSION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY_ID}
      - AWS_CLOUDFRONT_URL=${AWS_CLOUDFRONT_URL}
      - DEFAULT_AVATAR_IMG_URL=${DEFAULT_AVATAR_IMG_URL}
    restart: on-failure
