version: '3.9'

services:
  app:
    image: sand050965/miniroom
    container_name: app
    ports:
      - "3000:3000"
    env_file: ./.env
    restart: on-failure

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
