version: '3.9'

services:
  app:
    image: sand050965/miniroom
    container_name: app
    ports:
      - "8080:8080"
    env_file: ./.env
    restart: on-failure
    depends_on:
      - redis
    networks:
      - my_bridge

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - my_bridge
  
  redis:
    image: redis:latest
    container_name: redis
    restart: on-failure
    ports:
        - "6379:6379"
    volumes:
        - /home/ubuntu/redis-data:/data
    networks:
        - my_bridge
  
networks:
  my_bridge:
    external: true
