version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - peerjs

  peerjs:
    image: peerjs/peerjs-server
    container_name: peerjs
    ports:
      - "9000:9000"
    restart: on-failure